version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    hostname: letsdate  
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      
    ports:
      - ${PGADMIN_PORT}:80
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
